<?php

/**
 * @file
 * Module implementation file.
 */

use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Url;

/**
 * Implements hook_page_attachments_alter().
 */
function pager_metadata_page_attachments_alter(array &$attachments) {
  $cache = CacheableMetadata::createFromRenderArray($attachments);

  foreach ($attachments['#attached']['html_head'] as &$attachment) {
    if ($attachment[1] == 'canonical_url') {
      $url = Url::fromUri($attachment[0]['#attributes']['href']);
      $query = $url->getOption('query');
      if ($page = Drupal::service('pager.parameters')->findPage()) {
        if ($page > 0) {
          $query['page'] = $page;
        }
      }
      if (is_array($query)) {
        $url->setOption('query', $query);
      }
      $attachment[0]['#attributes']['href'] = $url->toString();

      // So the URL can be different for each page.
      $cache->addCacheContexts(['url.query_args.pagers']);
    }
  }

  $cache->applyTo($attachments);
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @link https://www.drupal.org/project/drupal/issues/1567684#comment-13631375
 */
function pager_metadata_preprocess_pager(&$pager) {
  $url = Url::fromRoute('<current>', [], ['absolute' => TRUE]);
  foreach ([
    'prev' => 'previous',
    'next' => 'next',
  ] as $rel => $item) {
    if (!empty($pager['items'][$item])) {
      $url->setOption('query', Url::fromUserInput($pager['items'][$item]['href'])
        ->getOption('query'));
      $pager['#attached']['html_head_link'][] = [
        [
          'rel' => $rel,
          'href' => $url->toString(),
        ],
        TRUE,
      ];
    }
  }
}

/**
 * Implements hook_block_build_alter().
 *
 * @link https://www.drupal.org/project/drupal/issues/2769953#comment-12561253
 */
function pager_metadata_block_build_alter(array &$build, BlockPluginInterface $block) {
  if ($block->getBaseId() == 'views_block') {
    // To make sure the pager preprocess can still insert something the head.
    $build['#create_placeholder'] = FALSE;
  }
}
